### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp'

### ISSUE THREAD

**Issue by faveoled** [alexandrehtrb/Pororoca#73]
Latest deb, Ubuntu 22.04.3
```
$ pororoca 
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/bin/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/bin/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/bin/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/bin/liblibSkiaSharp: cannot open shared object file: No such file or directory

   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Pororoca.Desktop.Program.Main(String[] args) in /home/runner/work/Pororoca/Pororoca/src/Pororoca.Desktop/Program.cs:line 17
Aborted (core dumped)

```

**Comment by alexandrehtrb** [comment]
@faveoled , to run Pororoca installed on Debian, from the command-line, please try:

```bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/pororoca pororoca
```

**Comment by faveoled** [comment]
Yes that works

**Comment by alexandrehtrb** [comment]
Solved, you can now launch Pororoca on Debian/Ubuntu via Terminal
